.github/workflows/upload_component.yml
.gitmodules
nghttp/CMakeLists.txt
nghttp/LICENSE
nghttp/README.md
nghttp/idf_component.yml
nghttp/port/include/nghttp2/nghttp2ver.h
nghttp/port/private_include/config.h
sh2lib/CMakeLists.txt
sh2lib/LICENSE
sh2lib/README.md
sh2lib/idf_component.yml
sh2lib/sh2lib.c
sh2lib/sh2lib.h

- Add nghttp (HTTP/2 C Library) component
- Add sh2lib (HTTP2 + TLS abstraction) component

Feature: Add nghttp and sh2lib components

---

expat/idf_component.yml
expat/port/include/expat_config.h

Detailed changelog: https://github.com/libexpat/libexpat/blob/R_2_4_3/expat/Changes

expat: upgrade to v2.4.3 release

---

.github/workflows/upload_component.yml
.gitmodules
coap/CMakeLists.txt
coap/Kconfig
coap/LICENSE
coap/README.md
coap/idf_component.yml
coap/port/include/coap3/coap.h
coap/port/include/coap_config.h
coap/port/include/coap_config_posix.h
coap/port/src/coap_mbedtls.c

Add libcoap to Component Manager

Add libcoap to Component Manager

---

.github/workflows/build_and_run_test_app.yml
README.md

This cathces regressions on 4.3, 4.4 and latest release branches
Closes #26

ci: Run nightly tests

---

.github/PULL_REQUEST_TEMPLATE/new_component.md
.github/PULL_REQUEST_TEMPLATE/update_component.md

Add Pull requests templates

---

.github/workflows/upload_component.yml
usb/test_app/CMakeLists.txt
usb/usb_host_msc/CMakeLists.txt
usb/usb_host_msc/LICENCE
usb/usb_host_msc/README.md
usb/usb_host_msc/idf_component.yml
usb/usb_host_msc/include/msc_host.h
usb/usb_host_msc/include/msc_host_vfs.h
usb/usb_host_msc/private_include/diskio_usb.h
usb/usb_host_msc/private_include/msc_common.h
usb/usb_host_msc/private_include/msc_scsi_bot.h
usb/usb_host_msc/src/diskio_usb.c
usb/usb_host_msc/src/msc_host.c
usb/usb_host_msc/src/msc_host_vfs.c
usb/usb_host_msc/src/msc_scsi_bot.c
usb/usb_host_msc/test/CMakeLists.txt
usb/usb_host_msc/test/msc_device.c
usb/usb_host_msc/test/test_common.h
usb/usb_host_msc/test/test_msc.c

USB host MSC class moved from IDF to idf-extra-components

usb host msc class

---

expat/idf_component.yml
expat/port/include/expat_config.h

expat: update to release R_2_4_8
Detailed changelog:
https://github.com/libexpat/libexpat/releases/tag/R_2_4_8
https://github.com/libexpat/libexpat/blob/R_2_4_8/expat/Changes

expat: update to release R_2_4_8

---

.github/workflows/build_and_run_test_app_usb.yml
pcap/CMakeLists.txt
pcap/idf_component.yml
pcap/include/pcap.h
pcap/src/pcap.c
usb/usb_host_cdc_acm/CMakeLists.txt
usb/usb_host_cdc_acm/cdc_acm_host.c
usb/usb_host_cdc_acm/idf_component.yml

Closes https://github.com/espressif/idf-extra-components/issues/69
Adding USB test_app to CI

usb: Run test_app in CI

---

.github/workflows/upload_component.yml
.gitmodules
eigen/CMakeLists.txt
eigen/LICENSE
eigen/README.md
eigen/idf_component.yml
test_app/CMakeLists.txt

Add Eigen library to the IDF.
Component working with Eigen library below version 3.4.

Add Eigen port to ESP

---

esp_encrypted_img/README.md
esp_encrypted_img/tools/esp_enc_img_gen.py

esp_encrypted_img: allow RSA public key for encryption purpose

---

eigen/examples/svd/CMakeLists.txt
eigen/examples/svd/README.md
eigen/examples/svd/main/CMakeLists.txt
eigen/examples/svd/main/idf_component.yml
eigen/examples/svd/main/main.cpp
eigen/examples/svd/sdkconfig.defaults
eigen/idf_component.yml

- [x ] Component contains License
- [ x] Component contains README.md
- [ x] Component contains idf_component.yml file with `url` field defined
- [ x] Component was added to [upload job](https://github.com/espressif/idf-extra-components/blob/master/.github/workflows/upload_component.yml#L18)
- [x ] Component was added to [build job](https://github.com/espressif/idf-extra-components/blob/master/test_app/CMakeLists.txt#L8)
This PR add example to the Eigen component directory that shows 
how to use the eigen library and IDF Eigen component.
Regards,
Dmitry

Example for Eigen idf component

---

eigen/idf_component.yml

This is update for component manager file with lates version number.

Update version for compoent manager

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/other-issue.yml

Adding issue templates into repository. Please check the templates and let me know if the provided documentation, description, requested data or whole templates make sense.

Add issue templates

---

led_strip/CHANGELOG.md
led_strip/README.md
led_strip/examples/led_strip_rmt_ws2812/CMakeLists.txt
led_strip/examples/led_strip_rmt_ws2812/README.md
led_strip/examples/led_strip_rmt_ws2812/main/CMakeLists.txt
led_strip/examples/led_strip_rmt_ws2812/main/idf_component.yml
led_strip/examples/led_strip_rmt_ws2812/main/led_strip_rmt_ws2812_main.c
led_strip/idf_component.yml
led_strip/include/led_strip_types.h
led_strip/src/led_strip_rmt_dev.c

Added led strip example.
Closes https://github.com/espressif/idf-extra-components/issues/145
Closes https://github.com/espressif/idf-extra-components/issues/155

led_strip: added example

---

.github/workflows/issue_comment.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml

Adding workflows for mirroring of issues from GitHub to Jira

Adding workflows for GH -> Jira issue mirroring

---

usb/esp_tinyusb/CMakeLists.txt
usb/esp_tinyusb/Kconfig
usb/esp_tinyusb/idf_component.yml
usb/esp_tinyusb/include/tinyusb_net.h
usb/esp_tinyusb/include/tusb_tasks.h
usb/esp_tinyusb/include_private/usb_descriptors.h
usb/esp_tinyusb/tinyusb.c
usb/esp_tinyusb/tinyusb_net.c
usb/esp_tinyusb/tusb_cdc_acm.c
usb/esp_tinyusb/tusb_tasks.c
usb/esp_tinyusb/usb_descriptors.c

Reworked https://github.com/espressif/idf-extra-components/pull/154

esp_tinyusb: USB device Network class (NCM)

---

.github/workflows/build_and_run_examples.yml
.ignore_build_warnings.txt

Fix build failure due to pkg_resources deprecation warning

---

.gitmodules
fmt/CMakeLists.txt
fmt/idf_component.yml

Updates fmt to the latest version.

fmt: Update to latest version(10.1.0) (IEC-38)

---

led_strip/CHANGELOG.md

contorl leds -> control leds
Use stronger active voice to recommend DMA in SPI mode.
contorl leds -> control leds
Use stronger active voice to recommend DMA in SPI mode.

led_strip: Update CHANGELOG.md with typo fix (IEC-52)

---

.github/workflows/build_and_run_examples.yml
.github/workflows/build_and_run_test_app.yml
.github/workflows/build_and_run_test_app_usb.yml
.github/workflows/clang-tidy.yml
.github/workflows/issue_comment.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml
.github/workflows/vulnerability_scan.yml

* Update CodeQL action
* Don't run Espressif specific GH actions in forks
Closes https://github.com/espressif/idf-extra-components/issues/221

CI: Maintanance

---

usb/usb_host_cdc_acm/cdc_acm_host.c

Update cdc_acm_host.c (IEC-66)

---

usb/usb_host_cdc_acm/CHANGELOG.md
usb/usb_host_cdc_acm/cdc_acm_host.c
usb/usb_host_cdc_acm/idf_component.yml

Related to issues:
* https://github.com/espressif/esp-idf/issues/12283
* https://github.com/espressif/esp-idf/issues/12503

fix(usb/cdc_host): Check endpoint pointers before accessing them

---

zlib/idf_component.yml
zlib/sbom_zlib.yml

Please see release notes at:
https://github.com/madler/zlib/releases/tag/v1.3

zlib: update to v1.3 release

---

usb/esp_tinyusb/idf_component.yml
usb/usb_host_cdc_acm/idf_component.yml
usb/usb_host_hid/idf_component.yml
usb/usb_host_msc/idf_component.yml
usb/usb_host_uvc/idf_component.yml
usb/usb_host_vcp/idf_component.yml

Changes in the `idf_component.yml` component files: 
- Added `## IDF Component Manager Manifest File` line where absent
- Added `esp32p4` target

feat(usb/host): Update manifest files for USB Host components

---

usb/esp_modem_usb_dte/CHANGELOG.md
usb/esp_modem_usb_dte/esp_modem_usb.cpp

Fix CI warnings with missing struct initializer in C++ code.

fix(usb/host): Fix build C++ build for newly added enum filter feature (IEC-80)

---

thorvg/CMakeLists.txt
thorvg/idf_component.yml
thorvg/project_include.cmake

Don't always install meson, let's detect if it's installed first.

fix(thorvg): install meson build system conditionally

---

coap/port/include/coap_config_posix.h
coap/sbom_libcoap.yml

Align SBOM version for coap component

fix(coap): correct sbom version as per component release

---

led_strip/Doxyfile
led_strip/api.md
led_strip/include/led_strip.h

Closes https://github.com/espressif/idf-extra-components/issues/345
change api description of hsv in api.md

docs(led_strip): change api description of hsv (IEC-131)

---

esp_encrypted_img/CHANGELOG.md
esp_encrypted_img/idf_component.yml
esp_encrypted_img/project_include.cmake

Closes https://github.com/espressif/idf-extra-components/issues/349

fix(esp_encrypted_img): correct the dependency for generating encrypted image

---

network_provisioning/CMakeLists.txt
network_provisioning/src/scheme_ble.c

Reduce restrictions for the scheme_ble source including

fix(network_prov): Reduce restrictions for the scheme_ble source including (IEC-163)

---

esp_delta_ota/examples/https_delta_ota/tools/esp_delta_ota_patch_gen.py

Added the new function in esp_delta_ota_patch_gen.py which verifies the newly generated patch file.
Added a new function in esp_delta_ota_patch_gen.py which verifies the newly generated patch file. The function uses the patch.bin and applies over base_binary.bin and calculates the sha of newly generate new.bin file. Then it compares this sha with the sha of new_binary.bin file. If they are same then it is verifies successfully otherwise invalid.

feat(https_delta_ota): Added new function to verify the patch file

---

zlib/idf_component.yml
zlib/sbom_zlib.yml

- Please see release notes at: https://github.com/madler/zlib/releases/tag/v1.3.1
- Fixes CVE-2023-45853

feat(zlib): update to release v1.3.1

---

zlib/sbom_zlib.yml

fix(zlib): exclude CVE-2023-45853 from scan (fixed in 1.3.1)

---

expat/idf_component.yml
expat/port/include/expat_config.h
expat/sbom_libexpat.yml

expat has been upgraded to 2.7.0
https://github.com/libexpat/libexpat/releases/tag/R_2_7_0

feat(expat): Upgrade the expat to 2.7.0

---

freetype/idf_component.yml
freetype/sbom_freetype.yml

Reverts version upgrade in `sbom_component.yml` and increments in `idf_component.yml`
This should fix the vulnerability scan

change(freetype): update version number in correct file (IEC-284)

---

.github/setup_qemu.sh
.github/workflows/build_and_run_apps.yml
esp_encrypted_img/test_apps/main/CMakeLists.txt
esp_encrypted_img/test_apps/main/esp_encrypted_img_test.c
esp_encrypted_img/test_apps/pytest_esp_encrypted_img.py
pytest.ini

This MR adds support for QEMU runner to run tests in the pipeline

feat: Add support for QEMU test runner

---

led_strip/src/led_strip_spi_dev.c

Closes https://github.com/espressif/idf-extra-components/issues/520

fix(led_strip): add model check in spi backend

---

.github/workflows/build_and_run_apps.yml

Remove IDF 5.0 build/test support - release is EOL

---

cbor/examples/cbor/main/cbor_example_main.c
cbor/idf_component.yml

- Release notes: https://github.com/intel/tinycbor/releases/tag/v0.6.1
- Closes https://github.com/espressif/idf-extra-components/issues/538

feat: update tinycbor to v0.6.1 release

---

sh2lib/examples/http2_request/main/http2_request_example_main.c
sh2lib/idf_component.yml
sh2lib/sh2lib.c
sh2lib/sh2lib.h

- Closes https://github.com/espressif/idf-extra-components/issues/525

fix(sh2lib): update API documentation for return values

---

expat/idf_component.yml
expat/port/include/expat_config.h
expat/sbom_libexpat.yml

This PR updates the expat to v2.7.2. This update fixes a security vulnerability [CVE-2025-59375](https://nvd.nist.gov/vuln/detail/CVE-2025-59375)

feat(expat): Update to v2.7.2

---

network_provisioning/CMakeLists.txt
network_provisioning/idf_component.yml

feat(network_prov): use managed component "espressif/cjson"
