.github/workflows/build_test.yml
Build test app also for ESP32S3, C3 on idf >= v4.3
ESP32S2 has less RAM, so the test_app will not fit.
=> Extend test_app builds

esp_encrypted_img/README.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/src/esp_encrypted_img.c
In this PR:
* Updated `esp_encrypted_img` component to add support for mbedtls-3.1 APIs.
* Updated README.md of `esp_encrypted_img` component for rendering in [Component Manager](https://components.espressif.com/component/espressif/esp_encrypted_img)
=> pre_encrypted_img: Updated component to support mbedtls-3.1 APIs

esp_encrypted_img/idf_component.yml, esp_encrypted_img/src/esp_encrypted_img.c
Updated code to fix unused variable error during build
=> esp_encrypted_img: fix for unused variable error during build

.github/workflows/build_and_run_test_app.yml, .github/workflows/pre-commit.yml, esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h, esp_encrypted_img/src/esp_encrypted_img.c, esp_encrypted_img/test/test.c, esp_encrypted_img/tools/esp_enc_img_gen.py, libsodium/port/randombytes_esp32.c
Love the `esp_encrypted_img` component and I've been trying it out in a C++ ESP IDF project, 
this PR just addresses a few small issues I found.
The first is that the `esp_encrypted_img_<whateever>` functions currently accept `esp_decrypt_handle_t*` parameter rather than a `esp_decrypt_handle_t`.
This is not correct and produces compiler errors in C++ (`esp_decrypt_handle_t` is already the handle pointer) 
The next is that there seemed a bunch of unnecessary memory allocations with (`calloc()`), moving the `gcm_key` and `iv` directly into the `esp_encrypted_img_handle` only adds 48 bytes to it (and it is already dynamically allocated), 
and also simplifies the setup/error handling. Likewise, `got_auth` is only 16 bytes and can be allocated on the stack.
Finally, there was a possible …
=> Some fixes/enhancements for esp_encrypted_img

esp_encrypted_img/README.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h
Sorry for the extra PR, this is just a very quick follow up to update the doc comments to reflect the changes from #17 
(forgot to update them)
I've also fixed a formatting issue in the README
=> esp_encrypted_img: fix doc comments and readme formatting

libsodium/idf_component.yml
This breaks alignment with upstream libsodium versioning.
But, libsodium doesn't use semantic versioning;
version 1.0.18 is being continuously updated. (https://download.libsodium.org/libsodium/releases/)
Closes #19
=> libsodium: Bump version to 1.0.19

esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h, esp_encrypted_img/src/esp_encrypted_img.c
Me again, `pre_enc_decrypt_arg_t.data_in` is not modified so can be `const`.
Without this change in C++ you have to add a bunch of `const_cast<char*>` to workaround this, if your inputs are marked const.
=> esp_encrypted_img: make code const-correct

libsodium/idf_component.yml, libsodium/port/crypto_hash_mbedtls/crypto_hash_sha256_mbedtls.c, libsodium/port/crypto_hash_mbedtls/crypto_hash_sha512_mbedtls.c
- Added `MBEDTLS_ALLOW_PRIVATE_ACCESS` to access private struct members wherever necessary (keeping backward compatibility)
- Updated deprecated functions from hashing module (E.g. `mbedtls_sha256_starts_ret()` -> `mbedtls_sha256_starts()`)
=> `libsodium`: Added forward compatibility with `mbedtls-3.x`

.github/filter_sarif.py, .github/workflows/clang-tidy.yml, README.md
One of the options to address https://github.com/espressif/idf-extra-components/issues/25.
1. https://github.com/espressif/clang-tidy-runner is used to run clang-tidy on the test app
2. Resulting warnings.txt file is converted to SARIF format using https://github.com/psastras/sarif-rs/tree/main/clang-tidy-sarif
3. At this point, the issues list contains also warnings reported for ESP-IDF source code. We use `filter_sarif.py` to include only issues reported for the source code from this repository. At the same time, we convert absolute paths to relative, which helps Github associate the issue with the file in the repository.
4. Resulting filtered SARIF file is uploaded to Github as Code Quality result.
Note that the CI job takes about 12 minutes to run. Not sure if it's okay to run it for …
=> ci: add static analysis with clang-tidy

.github/workflows/build_and_run_test_app.yml
Fix the initial slack off solution of `runs-on` tags.
This fixes the failing nightly tests.
=> ci: Check runner labels

sh2lib/idf_component.yml, sh2lib/sh2lib.c, sh2lib/sh2lib.h
Changes:
1) Enabled support for esp_crt_bundle with esp_tls.
=> sh2lib: Bump version to 1.0.1

.github/workflows/build_and_run_test_app.yml
espressif/idf/release-v4.3 branch reverted newer (>2.17) git version. So we need to use GH action checkout @v1
=> ci: Fix IDF v4.3 build

.github/workflows/clang-tidy.yml
- upgrade clang-tidy-runner to 0.2.0.
- use new '--include-paths' and '--exclude-paths' arguments of
clang-tidy-runner to limit the issues reported.
- don't install codereport and don't build an HTML report, fixing
the Jinja2 version incompatibility issue.
=> ci: clang-tidy fixes

sh2lib/idf_component.yml, sh2lib/sh2lib.c
- Update deprecated API `esp_tls_conn_http_new` with `esp_tls_conn_http_new_sync`
- __Note:__ The new API is merged in ESP-IDF `master` at https://github.com/espressif/esp-idf/commit/864c59c091f0711d0f7062be919d1e8aae5ec13e.
=> `sh2lib`: Update deprecated `esp_tls` API

coap/CMakeLists.txt, coap/idf_component.yml, pcap/CMakeLists.txt, pcap/idf_component.yml, sh2lib/CMakeLists.txt, sh2lib/idf_component.yml
This is the first step to fix IDF's format warnings.
IDF has globally enabled compiler option `-Wno-format`. The fix will be in three steps:
1. add `-Wno-format` to affected components
2. disable the global option  `-Wno-format`
3. fix format warnings for each component
=> Ignore format warnings

coap/CMakeLists.txt, coap/idf_component.yml
Added `-Wno-format` argument which was accidentally removed with https://github.com/espressif/idf-extra-components/pull/75
See https://github.com/espressif/idf-extra-components/pull/64 for more details
=> coap: ignore format warnings

coap/idf_component.yml, coap/port/include/coap_config_posix.h
- Updated submodule to fix Mbed TLS v3.2.1-related build errors
- Upstream PR: https://github.com/obgm/libcoap/pull/893
=> coap: Updated submodule to fix Mbed TLS `v3.2.1`-related errors

.github/workflows/clang-tidy.yml
clang-tidy-sarif was downgraded to v0.3.1 in https://github.com/espressif/idf-extra-components/pull/80; The author has released a new version since then, this PR does the upgrade.
=> ci: upgrade clang-tidy-sarif to v0.3.3

.github/workflows/build_and_run_test_app.yml, .github/workflows/build_test_app_usb.yml
Build with -Werror to prevent new warnings from being introduced. The set of extra warning flags matches ESP-IDF internal CI builds.
Closes https://github.com/espressif/idf-extra-components/issues/79
=> ci: build with extra warnings and -Werror

.github/workflows/upload_component.yml, bdc_motor/CMakeLists.txt, bdc_motor/LICENSE, bdc_motor/README.md, bdc_motor/idf_component.yml, bdc_motor/include/bdc_motor.h, bdc_motor/interface/bdc_motor_interface.h, bdc_motor/src/bdc_motor.c, bdc_motor/src/bdc_motor_mcpwm_impl.c, test_app/CMakeLists.txt
Copied from [the BDC example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/mcpwm/mcpwm_bdc_speed_control/components/bdc_motor)
The interface there should be much close to a "stable" one, so it's time to publish it to the component registry.
No test_app is added for now, but we have one test in the esp-idf example.
=> bdc_motor: added BDC motor control library

.github/workflows/upload_component.yml, led_strip/CMakeLists.txt, led_strip/LICENSE, led_strip/README.md, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/interface/led_strip_interface.h, led_strip/src/led_strip_api.c, led_strip/src/led_strip_rmt_dev.c, led_strip/src/led_strip_rmt_encoder.c, led_strip/src/led_strip_rmt_encoder.h, test_app/CMakeLists.txt
Moved from [ESP-IDF example common component](https://github.com/espressif/esp-idf/tree/master/examples/common_components/led_strip).
Previously the led_strip (version 1) has been deprecated, and this new version is based on the new RMT driver in ESP-IDF 5.0.
=> led_strip: added led strip driver v2

.github/workflows/build_and_run_test_app.yml, .github/workflows/build_and_run_test_app_usb.yml
New version of `cryptography` was released yesterday, but piwheels.org doesn't have a wheel for it yet.
Switch to dl.espressif.com/pypi as the extra source of wheels and prefer installing a version of `cryptography` from a binary wheel.
Fixes pipeline failures such as https://github.com/espressif/idf-extra-components/runs/8252043014
Port of a fix by @mahavirj in esp-protocols repository, https://github.com/espressif/esp-protocols/commit/64e31dae4829fb700ea0c461d8dd077b6340f5d4.
=> ci: use dl.espressif.com/pypi for wheels, install cryptography wheel

.github/workflows/build_and_run_test_app_usb.yml, usb/usb_host_cdc_acm/test/usb_device.c, usb/usb_host_msc/idf_component.yml, usb/usb_host_msc/src/msc_host_vfs.c, usb/usb_host_msc/test/msc_device.c, usb/usb_host_uvc/src/descriptor.c
Since API of `fatfs` has changed between IDF versions v4.4 and 5.0, compile time condition was added in order to cover both.
=> usb_host_msc: Fix compatibility with IDF v4.4

.github/workflows/upload_component.yml, esp_serial_slave_link/CMakeLists.txt, esp_serial_slave_link/LICENSE, esp_serial_slave_link/README.md, esp_serial_slave_link/essl.c, esp_serial_slave_link/essl_internal.h, esp_serial_slave_link/essl_sdio.c, esp_serial_slave_link/essl_spi.c, esp_serial_slave_link/idf_component.yml, esp_serial_slave_link/include/esp_serial_slave_link/essl.h, esp_serial_slave_link/include/esp_serial_slave_link/essl_sdio.h, esp_serial_slave_link/include/esp_serial_slave_link/essl_spi.h, esp_serial_slave_link/include/essl_spi/esp32c2_defs.h, esp_serial_slave_link/include/essl_spi/esp32c3_defs.h, esp_serial_slave_link/include/essl_spi/esp32s2_defs.h, esp_serial_slave_link/include/essl_spi/esp32s3_defs.h, test_app/CMakeLists.txt
Moving this component from IDF to extra components, since it's upper layer component.
Tracking ESP-IDF commit: [4f1a9e436e](https://github.com/espressif/esp-idf/commit/4f1a9e436e)
=> Add essl to component manager

usb/usb_host_msc/src/msc_host.c
Transfer timeout increased from 1 second to 5 seconds (as recommended in USB specs).
Shorter timeout caused undesired behavior on some USB flash drives, such as re-connection issues: 
https://github.com/espressif/esp-idf/issues/9619
=> USB MSC Transfer timeout increased to 5 seconds.

esp_jpeg/README.md, esp_jpeg/idf_component.yml
After notification on Mattermost, I fixing bad list of MCUs, which have TjpgDec in ROM.
=> esp_jpeg: Fixed list of MCUs with TjpgDec in ROM in Readme

.github/workflows/upload_component.yml, usb/esp_tinyusb/CMakeLists.txt, usb/esp_tinyusb/Kconfig, usb/esp_tinyusb/LICENSE, usb/esp_tinyusb/README.md, usb/esp_tinyusb/cdc.c, usb/esp_tinyusb/descriptors_control.c, usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/tinyusb.h, usb/esp_tinyusb/include/tinyusb_types.h, usb/esp_tinyusb/include/tusb_cdc_acm.h, usb/esp_tinyusb/include/tusb_config.h, usb/esp_tinyusb/include/tusb_console.h, usb/esp_tinyusb/include/tusb_tasks.h, usb/esp_tinyusb/include/vfs_tinyusb.h, usb/esp_tinyusb/include_private/cdc.h, usb/esp_tinyusb/include_private/descriptors_control.h, usb/esp_tinyusb/include_private/usb_descriptors.h, usb/esp_tinyusb/tinyusb.c, usb/esp_tinyusb/tusb_cdc_acm.c, usb/esp_tinyusb/tusb_console.c, usb/esp_tinyusb/tusb_tasks.c, usb/esp_tinyusb/usb_descriptors.c, usb/esp_tinyusb/vfs_tinyusb.c, usb/test_app/main/idf_component.yml
In IDF v5.0, TinyUSB submodule is removed. It was replaced by `esp_tinyusb` component. At the moment, version 0.0.1 of esp_tinyusb is a monolithic component: TinyUSB + Espressif additions.
This PR separates the two. The user can choose whether he wants 'pure' TinyUSB, or the 'v4.x style' additions.
This PR contains the 'additions' part that depends on 'pure' TinyUSB = `esp_tinyusb` component.
Related: espressif/tinyusb component proposal: https://github.com/espressif/tinyusb/pull/5
=> usb: Add esp_tinyusb component

coap/idf_component.yml, coap/port/include/coap_config_posix.h
Upgrade CoAP to release v4.3.1
changelog: https://github.com/obgm/libcoap/blob/v4.3.1/ChangeLog
=> coap: Upgrade libcoap to release v4.3.1

bdc_motor/README.md, eigen/README.md, esp_encrypted_img/README.md, esp_jpeg/README.md, esp_serial_slave_link/README.md, fmt/README.md, jsmn/README.md, json_generator/README.md, json_parser/README.md, led_strip/README.md, pcap/README.md, pid_ctrl/README.md, qrcode/README.md, sh2lib/README.md, usb/esp_modem_usb_dte/README.md, usb/esp_tinyusb/README.md, usb/esp_tinyusb/idf_component.yml, usb/usb_host_cdc_acm/README.md, usb/usb_host_ch34x_vcp/README.md, usb/usb_host_cp210x_vcp/README.md, usb/usb_host_ftdi_vcp/README.md, usb/usb_host_msc/README.md, usb/usb_host_uvc/README.md, usb/usb_host_vcp/README.md
Created README.md file for pid_ctrl component.
Added badges with versions in README files to following components:
- bdc_motor
- eigen
- esp_encrypted_img
- esp_jpeg
- esp_serial_slave_link
- fmt
- jsmn
- json_generator
- json_parser
- led_strip
- pcap
- pid_ctrl
- qrcode
- sh2lib
- esp_modem_usb_dte
- esp_tiny_usb
- usb_host_cdc_acm
- usb_host_ch34x_vcp
- usb_host_cp210x_vcp
- usb_host_ftdi_vcp
- usb_host_msc
- usb_host_uvc
- usb_host_vcp
Added 
``` yml
documentation: "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/usb_device.html"
```
to the [usb/esp_tinyusb/idf_component.yml](https://github.com/espressif/idf-extra-components/blob/master/usb/esp_tinyusb/idf_component.yml)
=> Added badges with version to the README files of components

usb/esp_tinyusb/idf_component.yml
Semver has special handling of 0.x versions
Reference: https://devhints.io/semver
=> esp_tinyusb: Allow TinyUSB updates

led_strip/CHANGELOG.md, led_strip/README.md, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/include/led_strip_rmt.h, led_strip/include/led_strip_types.h, led_strip/src/led_strip_rmt_dev.c
This PR enables the user to select more clock sources for the led strip (RMT backend). 
DMA support can also be enabled optionally.
Restructured the component source file and updated the README file.
=> led_strip: support dma feature and various clock source

esp_serial_slave_link/CHANGELOG.md, esp_serial_slave_link/essl_sdio_defs.c, esp_serial_slave_link/idf_component.yml, esp_serial_slave_link/include/esp_serial_slave_link/essl_sdio.h, esp_serial_slave_link/include/esp_serial_slave_link/essl_sdio_defs.h
- Supported essl_sdio communicating with ESP32C6 SDIO Slave
- Upgrade to v1.1.0
=> essl_sdio: support communicating with esp32c6 sdio slave

usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/vfs_tinyusb.h, usb/esp_tinyusb/tusb_cdc_acm.c, usb/esp_tinyusb/tusb_console.c, usb/esp_tinyusb/vfs_tinyusb.c
1. Fix memory leak while returning in case of error. While returning in case of error, these should be called for freeing up the resources:
a. tinyusb_cdc_deinit()
b. free(acm->rx_tfbuf);
2. Remove unused 'initialized'
3. Remove hard coding of "/dev/tusb_cdc"
=> USB: esp_tinyusb - fix memory leak in case of error, refactoring

led_strip/CHANGELOG.md, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/include/led_strip_types.h, led_strip/interface/led_strip_interface.h, led_strip/src/led_strip_api.c, led_strip/src/led_strip_rmt_dev.c, led_strip/src/led_strip_rmt_encoder.c, led_strip/src/led_strip_rmt_encoder.h
Implementing support for RGBW leds, specifically for SK6812.
These devices have 4 leds, the standard three RGB ones and a fourth white led.
=> led_strip: support for 4 components RGBW leds (SK6812)

led_strip/README.md, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/include/led_strip_types.h, led_strip/interface/led_strip_interface.h, led_strip/src/led_strip_rmt_dev.c, led_strip/src/led_strip_rmt_encoder.c, led_strip/src/led_strip_rmt_encoder.h
Follow up of https://github.com/espressif/idf-extra-components/pull/126
No functional change, but update some API doc.
Bumped version: 2.2.0 -> 2.2.1
=> doc: update led_strip doc for pixel format and led model

esp_jpeg/Kconfig, esp_jpeg/idf_component.yml
ESP32H2's ROM doesn't contain the tjpgd library.
=> tjpgd: remove ROM support for esp32h2

esp_encrypted_img/idf_component.yml, esp_encrypted_img/src/esp_encrypted_img.c
While testing GCC-12 I found this error:
```
../managed_components/espressif__esp_encrypted_img/src/esp_encrypted_img.c: In function 'read_and_cache_data':
../managed_components/espressif__esp_encrypted_img/src/esp_encrypted_img.c:254:50: error: the comparison will always evaluate as 'true' for the address of 'iv' will never be NULL [-Werror=address]
254 |     if (handle->state == ESP_PRE_ENC_IMG_READ_IV && handle->iv) {
|                                                  ^~
../managed_components/espressif__esp_encrypted_img/src/esp_encrypted_img.c:46:10: note: 'iv' declared here
46 |     char iv[IV_SIZE];
|          ^~
```
=> esp_encrypted_img: fix gcc-12 compile errors

usb/usb_host_ch34x_vcp/idf_component.yml, usb/usb_host_ch34x_vcp/include/usb/vcp_ch34x.hpp, usb/usb_host_cp210x_vcp/idf_component.yml, usb/usb_host_cp210x_vcp/include/usb/vcp_cp210x.hpp, usb/usb_host_ftdi_vcp/idf_component.yml, usb/usb_host_ftdi_vcp/include/usb/vcp_ftdi.hpp
Fix for gcc-12 builds
The compile errors were:
```
In file included from ../main/cdc_acm_vcp_example_main.cpp:16:
../managed_components/espressif__usb_host_ch34x_vcp/include/usb/vcp_ch34x.hpp:56:46: error: 'constexpr const std::array<short unsigned int, 3> esp_usb::CH34x::pids' has incomplete type
56 |     static constexpr std::array<uint16_t, 3> pids = {CH340_PID, CH340_PID_1, CH341_PID};
|                                              ^~~~
In file included from ../main/cdc_acm_vcp_example_main.cpp:17:
../managed_components/espressif__usb_host_cp210x_vcp/include/usb/vcp_cp210x.hpp:108:46: error: 'constexpr const std::array<short unsigned int, 3> esp_usb::CP210x::pids' has incomplete type
108 |     static constexpr std::array<uint16_t, 3> pids = {CP210X_PID, CP2105_PID, CP2108_PID};
| …
```
=> usb: fix gcc-12 compile errors

led_strip/CHANGELOG.md, led_strip/idf_component.yml, led_strip/include/led_strip_rmt.h, led_strip/src/led_strip_rmt_dev.c
Introduce a new configuration entry: `mem_block_symbols` so that the channel block size can be customized by the user.
Closes https://github.com/espressif/idf-extra-components/issues/138
=> led_strip: support configurable channel block size

json_parser/idf_component.yml
Fix a compilation error of `json_parser` component on idf v4.x.
Because the jsmn component was part of idf v4.4 and earlier.
The compile errors were:
```c
ERROR: Cannot process component requirements.  Multiple candidates to
satisfy project requirements:
requirement: "jsmn" candidates: "espressif__jsmn, jsmn"
```
=> json_parser: add idf_version rules for jsmn

.github/workflows/build_and_run_test_app.yml
Release/v5.0 was already used in the usb and cbor workflows. This PR adds it to the common test_app as well.
=> ci: build and run the test app with release/v5.0

usb/esp_modem_usb_dte/esp_modem_usb.cpp, usb/usb_host_cdc_acm/CHANGELOG.md, usb/usb_host_cdc_acm/README.md, usb/usb_host_cdc_acm/cdc_acm_host.c, usb/usb_host_cdc_acm/idf_component.yml, usb/usb_host_cdc_acm/include/usb/cdc_acm_host.h, usb/usb_host_cdc_acm/test/test_cdc_acm_host.c, usb/usb_host_ftdi_vcp/include/usb/vcp_ftdi.hpp, usb/usb_host_ftdi_vcp/usb_host_ftdi_vcp.cpp, usb/usb_host_vcp/usb_host_vcp.cpp
- New function `cdc_acm_host_register_new_dev_callback`. This allows you to get New Device notifications even if you use the default driver, or you didn't install the driver yourself
- Receive buffer has configurable size. This is useful if you expect data transfers larger then Maximum Packet Size.
- Receive buffer has 'append' function. In the Data Received callback you can signal that you wait for more data and the current data were not yet processed. In this case, the CDC driver appends new data to the already received data. This is especially useful if the upper layer messages consist of multiple USB transfers and you don't want to waste more RAM and CPU copying the data around.
The last point^ is unfortunately a breaking change. Some cellular modems in …
=> USB: CDC-ACM enhacements

usb/esp_tinyusb/Kconfig, usb/esp_tinyusb/descriptors_control.c, usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/tinyusb.h, usb/esp_tinyusb/include/tinyusb_types.h, usb/esp_tinyusb/include/tusb_cdc_acm.h, usb/esp_tinyusb/include/tusb_config.h, usb/esp_tinyusb/include_private/descriptors_control.h, usb/esp_tinyusb/include_private/usb_descriptors.h, usb/esp_tinyusb/tinyusb.c, usb/esp_tinyusb/usb_descriptors.c
There are following changes:
* Cleanup TinyUSB string descriptors handling. Remove unused code. Add length check to arguments passed to `tinyusb_driver_install`
* Add private option to modify string descriptors
* Use latest [tinyusb](https://components.espressif.com/components/espressif/tinyusb) v0.14.2
* Update Kconfig and tusb_config.h for new feature (Bluetooth, NET, DFU)
~### Commit 97a108e686134149f250366e0fdd3703e7c80afc~
~* Proposal of MAC string handling for NET class~
~* Will be dropped~
Related #133 
I can split the PR into 2, if it is easier to review.
=> esp_tinyusb: String descriptor handling

.github/workflows/upload_component.yml
Unfortunately sorting the list of components in https://github.com/espressif/idf-extra-components/pull/160 had one disadvantage: if two new components are added in the same PR and the (alphabetically) 1st one depends on the 2nd one, the upload of the 1st component will fail (https://github.com/espressif/idf-extra-components/actions/runs/4512604342/jobs/7946288243).
This PR moves libpng to the end of the list so that it gets uploaded after zlib is uploaded for the first time. We can revert to the correct sorting order in a follow-up PR.
=> ci: fix libpng not uploaded since there's no zlib in the registry yet

nghttp/idf_component.yml, nghttp/port/include/nghttp2/nghttp2ver.h
Update nghttp version to v1.52.0
Binary Footprint: +120 Bytes
Memory Overhead: ~100 Bytes (average of 3 test runs)
=> nghttp: Update version to 1.52.0

usb/usb_host_msc/README.md, usb/usb_host_msc/idf_component.yml, usb/usb_host_msc/src/msc_host.c
1. remove unused variable 'lun'
2. usb composite device (msc + cdc) verified for its working.
=> usb msc host: remove unused variable lun

usb/usb_host_uvc/idf_component.yml
The version was not bumped during https://github.com/espressif/idf-extra-components/commit/7331abceabaaae5c9e905106bf0aa8c4938f7215
Closes https://github.com/espressif/esp-idf/issues/10581
=> usb: Bump UVC version

.github/workflows/upload_component.yml, ccomp_timer/CHANGELOG.md, ccomp_timer/CMakeLists.txt, ccomp_timer/LICENSE, ccomp_timer/README.md, ccomp_timer/ccomp_timer.c, ccomp_timer/ccomp_timer_impl_riscv.c, ccomp_timer/ccomp_timer_impl_xtensa.c, ccomp_timer/idf_component.yml, ccomp_timer/include/ccomp_timer.h, ccomp_timer/private_include/ccomp_timer_impl.h, ccomp_timer/test/CMakeLists.txt, ccomp_timer/test/ccomp_timer_test_api.c, ccomp_timer/test/ccomp_timer_test_data.c, ccomp_timer/test/ccomp_timer_test_inst.c, test_app/CMakeLists.txt
Play around with git filter-repo, I managed to keep the git history. 
This ccomp_timer was previously located in the esp-idf's tools folder. We found it can be useful for other components' performance tests, so decide to push it to the component registry.
=> cache compensated timer for measuring performance metric

coap/CMakeLists.txt, coap/idf_component.yml, coap/port/src/block.c
Corrects combined packets re-assembly.
Thanks to Shang Zewen for reporting this issue and providing the information to reproduce it.
=> coap: Handle missing Size1 option when Block1 option is used (IEC-18)

led_strip/idf_component.yml, led_strip/src/led_strip_rmt_dev.c
` bytes_per_pixel` can be uninitialized if the assert is disabled.
Closes https://github.com/espressif/idf-extra-components/issues/177
=> led_strip: fix uninitialized bytes_per_pixel

usb/esp_tinyusb/CMakeLists.txt, usb/esp_tinyusb/README.md, usb/esp_tinyusb/idf_component.yml
cdc console feature is enabled only when VFS is enabled.
This is done by compiling the console feature related files only when VFS option is enabled.
If VFS is not enabled, compile error will be thrown. So, it will avoid runtime failure.
Closes https://github.com/espressif/idf-extra-components/issues/164
=> esp_tinyusb: cdc console feature is enabled only when VFS is enabled

esp_encrypted_img/CHANGELOG.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h, esp_encrypted_img/src/esp_encrypted_img.c, esp_encrypted_img/test/test.c
1) Fix structure member name in esp_decrypt_cfg_t 
1.1 `rsa_pub_key` to `rsa_priv_key`
1.2 `rsa_pub_key_len` to `rsa_priv_key_len`
2) Fix the return code  in the header file API description
=> esp_encrypted_img: fix structure member name in esp_decrypt_cfg_t

.build-test-rules.yml, led_strip/CMakeLists.txt, led_strip/README.md, led_strip/examples/led_strip_rmt_ws2812/main/idf_component.yml, led_strip/examples/led_strip_rmt_ws2812/main/led_strip_rmt_ws2812_main.c, led_strip/examples/led_strip_spi_ws2812/main/led_strip_spi_ws2812_main.c, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/include/led_strip_spi.h, led_strip/src/led_strip_spi_dev.c, test_app/CMakeLists.txt
Continue to the previous PR: https://github.com/espressif/idf-extra-components/pull/190
* Changed the dependency, now the led_strip still relies on the idf v5.0, instead of v5.1
* Updated the README to describe the new SPI backend usage and a diagram to help user choose which backend
=> led_strip: fix version dependency

usb/esp_modem_usb_dte/idf_component.yml, usb/test_app/main/usb_test_main.c, usb/test_app/pytest_usb_host.py, usb/usb_host_msc/CHANGELOG.md, usb/usb_host_msc/CMakeLists.txt, usb/usb_host_msc/idf_component.yml, usb/usb_host_msc/include/esp_private/msc_scsi_bot.h, usb/usb_host_msc/include/usb/msc_host.h, usb/usb_host_msc/include/usb/msc_host_vfs.h, usb/usb_host_msc/private_include/msc_common.h, usb/usb_host_msc/src/diskio_usb.c, usb/usb_host_msc/src/msc_host.c, usb/usb_host_msc/src/msc_host_vfs.c, usb/usb_host_msc/src/msc_scsi_bot.c, usb/usb_host_msc/test/test_common.h, usb/usb_host_msc/test/test_msc.c
- Significantly increase performance with Virtual File System by allowing longer transfers
- Optimize used heap memory by reusing the Virtual File System buffer
- Optimize CPU usage by putting the background MSC task to 'Blocked' state indefinitely when there is nothing to do
- Fix MSC commands for devices on interface numbers other than zero
- Replace unsafe debug functions for direct access of MSC sectors with private SCSI commands
After the application starts new USB transfer, the USB-OTG peripheral will schedule it for next frame (which can be as delayed as 1ms). Therefore, the application must submit large-enough (>1kB) transfers to fully leverage USB FullSpeed bandwidth. For larger USB transfers we need more DMA capable memory, plus we need the same amount for memory for buffer in …
=> USB MSC: speed optimization

.github/workflows/test_sbom.yml, .gitmodules
This adds SBOM information for submodules, which are not managed by Espressif. Meaning there is no fork for them in the espressif namespace. Other submodules should add sbom.yml manifest file to the root of their git repository.
The SBOM information for submodules is stored in the .gitmodules file. Each SBOM related variable has the "sbom-" prefix
=> Add sbom information for submodules

esp_jpeg/idf_component.yml
Sorry, I forgot to change the example path in the last PR, thus the CI still fails uploading the esp_jpeg example. https://github.com/espressif/idf-extra-components/actions/runs/5542032824/jobs/10116192367
=> bugfix(esp_jpeg): fix example uploading failure

json_parser/idf_component.yml
This reverts commit 7b08cd0df5978e4cace8321d5cd9823c053e0c5d.
The idf component manager now supports uploading components with rules.
This just reverts an earlier change which was added due to a bug in idf component manager, which did not allow external components to have "rules" in dependencies. Now that the bug is fixed, we can add back the rules.
=> Revert "Revert "json_parser: add idf_version rules for jsmn"" (IEC-29)

pid_ctrl/README.md, pid_ctrl/idf_component.yml, pid_ctrl/include/pid_ctrl.h, pid_ctrl/src/pid_ctrl.c
There are occasions when it is necessary to reset the previously accumulated error (e.g. when the motor is stopped and then started again). This commit add a reset_pre_error function in pid_ctrl. And fix a hyperlink error in pid_ctrl README.md
Closes https://github.com/espressif/idf-extra-components/issues/203
=> feature/add reset_pre_error in pid_ctrl (IEC-30)

usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/tusb_msc_storage.h, usb/esp_tinyusb/tusb_msc_storage.c
Add additional pre mount/unmount changed event and callback.
This will be delivered (if subscribed) BEFORE mount/unmount operation is started.
This will be helpful to the user who wants to be notified before the mount/unmount operation starts.
One such requirement is mentioned [here](https://esp32.com/viewtopic.php?f=13&t=34535).
=> esp_tinyusb: add MSC pre mount/unmount changed event and callback

esp_encrypted_img/CHANGELOG.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h, esp_encrypted_img/src/esp_encrypted_img.c, esp_encrypted_img/test/test.c
- Added an API to abort the decryption process in esp_encrypted_img: `esp_encrypted_img_decrypt_abort`
- Added an API to check if the complete data has been received: `esp_encrypted_img_is_complete_data_received`
=> feat: Add API to abort decryption process in esp_encrypted_img component

led_strip/README.md, led_strip/idf_component.yml, led_strip/src/led_strip_spi_dev.c
Since the spi driver has fixed the idle level of MOSI. Remove the operation which controls the register.
=> refactor(led_strip): Remove the hack code (IEC-37)

.github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/upload_component.yml, .gitmodules, freetype/CMakeLists.txt, freetype/LICENSE, freetype/README.md, freetype/idf_component.yml, test_app/CMakeLists.txt
Add a component of freetype, it's mainly used for LVGL.
=> components: add freetype (IEC-31)

usb/usb_host_cdc_acm/CHANGELOG.md, usb/usb_host_cdc_acm/cdc_acm_host.c, usb/usb_host_cdc_acm/idf_component.yml
I have number of USB devices that are simple CDC-ACM "serial" devices, but present themselves with  bDeviceClass, bDeviceSubClass, and bDeviceProtocol set to 0x00, which according to the standard (https://www.usb.org/defined-class-codes, Base Class 00h (Device) section) indicates that class information should be determined from the interface descriptors. The implementation to detect the device with the null triple is virtually identical to the already existing IAD device detection.
This change extends the device interface detection to also recognize devices with null class triple.
=> Add support for null class triple (IEC-40)

usb/esp_tinyusb/include/tinyusb.h, usb/esp_tinyusb/include/tusb_cdc_acm.h, usb/esp_tinyusb/tinyusb.c, usb/esp_tinyusb/tusb_cdc_acm.c
This makes it possible for user code to work around the bug where the USB/JTAG interface cannot be re-initialized after calling `tinyusb_driver_install` even if the chip is restarted with `esp_restart` (https://github.com/espressif/esp-idf/issues/9826#issuecomment-1694089147).
Currently user code cannot do this without a modification to `tinyusb.c` since there's no way to access `static usb_phy_handle_t phy_hdl;` outside of that file.
With this change, user code can run the following to deactivate TinyUSB and bring back the USB/JTAG interface.
```
tinyusb_driver_uninstall();
usb_phy_config_t phy_conf = {
.controller = USB_PHY_CTRL_SERIAL_JTAG,
};
usb_phy_handle_t jtag_phy;
usb_new_phy(&phy_conf, &jtag_phy);
```
=> Add a tinyusb_driver_uninstall to tinyusb.c (IEC-41)

esp_encrypted_img/CHANGELOG.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/include/esp_encrypted_img.h, esp_encrypted_img/src/esp_encrypted_img.c
This MR added the API to get the header size which helps in decryption during pre_encrypted_ota. This header size is helpful to check whether the complete image has been received or not during pre_encypted_ota and partial HTTP download config is set.
=> feat(esp_encrypted_img): feature added to get header size which helps… (IEC-45)

usb/esp_tinyusb/CHANGELOG.md, usb/esp_tinyusb/CMakeLists.txt, usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/tusb_msc_storage.h, usb/esp_tinyusb/tusb_msc_storage.c
This change makes maximum open files configurable. Currently it is set to 2.
Closes https://github.com/espressif/idf-extra-components/issues/217
=> Make max files configurable in tusb_msc_storage.c (IEC-44)

.github/workflows/test_sbom.yml, .gitmodules, catch2/idf_component.yml, catch2/sbom_catch2.yml, coap/idf_component.yml, coap/sbom_libcoap.yml, expat/idf_component.yml, expat/sbom_libexpat.yml, fmt/idf_component.yml, fmt/sbom_fmt.yml, freetype/idf_component.yml, freetype/sbom_freetype.yml, libpng/idf_component.yml, libpng/sbom_libpng.yml, nghttp/idf_component.yml, nghttp/sbom_nghttp2.yml, zlib/idf_component.yml, zlib/sbom_zlib.yml
The esp-idf-sbom tool now supports "referenced" manifests allowing to add sbom files for libraries, which we do not have control over. IOW submodules not managed by Espressif. This adds sbom manifests for such libraries.
Since we are moving away from keeping sbom information in `.gitmodules`, this PR removes sbom related variables from `.gitmodules`. We also need a different approach for `hash` checking and sbom manifest validation, because till now it was all based on the info in `.gitmodules` only. Latest `esp-idf-sbom` has a new command, which allows to validate specific sbom manifest files, .gitmodules and also directories, which are searched for any possible sbom manifest file(sbom.yml, referenced manifests, idf_component.yml, .gitmodules.) This allows to simply validate all …
=> feat: add sbom manifest files for 3rd party libraries (IEC-50)

usb/esp_tinyusb/CHANGELOG.md, usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/tusb_msc_storage.c
Fixes regression from #231 cc @pborcin 
Now we check if max_files is zero. If yes, we default to max_files = 2
Version 1.4.1  was deleted (not yanked) so we skip this version in the changelog
=> fix(usb/esp_tinyusb): Fix backward compatibility for MSC max_files

usb/usb_host_msc/CHANGELOG.md, usb/usb_host_msc/CMakeLists.txt, usb/usb_host_msc/README.md, usb/usb_host_msc/idf_component.yml, usb/usb_host_msc/include/usb/msc_host.h, usb/usb_host_msc/private_include/msc_common.h, usb/usb_host_msc/src/msc_host.c, usb/usb_host_msc/test/msc_device.c, usb/usb_host_msc/test/test_msc.c
* Correctly handle empty string descriptors
* Move data buffer to DMA capable memory, if non-capable memory is passed to the driver
PTAL @Dazza0 @roma-jam 
cc @leeebo @lijunru-hub @Maldus512 @0727fqh @f1andrew
Closes https://github.com/espressif/esp-idf/issues/12163
Closes https://github.com/espressif/idf-extra-components/issues/202
Closes https://github.com/espressif/esp-idf/issues/12142
=> USB Host MSC v1.1.1

usb/usb_host_hid/CHANGELOG.md, usb/usb_host_hid/CMakeLists.txt, usb/usb_host_hid/hid_host.c, usb/usb_host_hid/idf_component.yml, usb/usb_host_hid/include/usb/hid_host.h, usb/usb_host_hid/test/test_hid_basic.c, usb/usb_host_hid/test/test_hid_basic.h, usb/usb_host_hid/test/test_hid_err_handling.c
- Fixed a bug where configuring the driver with `create_background_task = false` did not properly initialize the driver. This lead to `the hid_host_uninstall()` hang-up.
- Fixed bug where `hid_host_uninstall()` would cause a crash during the call while USB device has not been removed.
- Added `hid_host_get_device_info()` to get the basic information of a connected USB HID device.
Fix `hid_host_uninstall()` hanging during the closing while driver was installed with `create_background_task = false` configuration.
Unit test `class_specific_requests_with_external_polling` has been added to the test cases.
When the `create_background_task = false` configuration is used, the `event_handler_task` is not being created. Thus, the `hid_host_handle_events()` should be called periodically to handle …
=> fix(usb/hid): HID Host Driver v.1.0.1

.github/workflows/vulnerability_scan.yml
esp-idf-sbom allows to scan whole repository/directory for all possible manifest files(idf_component.yml, sbom.yml and its referenced manifests, .gitmodules) and check them for possible vulnerabilities based on the cpe variable in manifest.
This adds scheduled scan at every midnight and also ad hoc(dispatch workflow) allowing to scan on demand.
=> feat(ci): add periodic and ad hoc vulnerability scan

.github/workflows/upload_component.yml
Verify components in PRs by running the upload action with --dry-run argument (based on https://github.com/espressif/upload-components-ci-action/pull/12)
Will hopefully prevent issues like https://github.com/espressif/idf-extra-components/pull/219 and https://github.com/espressif/idf-extra-components/pull/161.
=> check components in PRs

.build-test-rules.yml, led_strip/CHANGELOG.md, led_strip/CMakeLists.txt, led_strip/README.md, led_strip/examples/led_strip_rmt_ws2812/main/led_strip_rmt_ws2812_main.c, led_strip/idf_component.yml, led_strip/include/led_strip.h, led_strip/include/led_strip_rmt.h, led_strip/src/led_strip_api.c, led_strip/src/led_strip_rmt_dev_idf4.c, qrcode/idf_component.yml
Updated LED Strip component for working with IDF4.4 (only with RMT)
=> led_strip: Support for IDF4.4

.pre-commit-config.yaml
Fixes Pyyaml and Cython version incompatibility (https://github.com/espressif/idf-extra-components/actions/runs/6665480199/job/18115381366?pr=262)
=> fix(pre-commit): update astyle_py to 1.0.5

sh2lib/examples/http2_request/main/http2_request_example_main.c
Fixes a regression from https://github.com/espressif/esp-idf/commit/a71fa821 where we introduce `esp_netif_sntp_init()`, but didn't correctly deinit in some examples
=> fix(sh2lib): Deinit SNTP correctly with IDF>=5.1 (IEC-68)

libsodium/CMakeLists.txt, libsodium/idf_component.yml, libsodium/port_include/sodium/version.h
- There is an inconsistency in the component and upstream version. This is because, the upstream libsodium had stopped creating new releases sometimes back and used to update same revision. This time around they created new semantic version but the IDF version was already updated earlier. Hence, in this change, only the `revision` field is added for the component.
- Synced the version.h file with upstream
Closes https://github.com/espressif/idf-extra-components/issues/257
=> feat(libsodium): use latest 1.0.19 upstream release

.gitignore, led_strip/CHANGELOG.md, led_strip/README.md, led_strip/api.md, led_strip/idf_component.yml, led_strip/include/led_strip_rmt.h, led_strip/include/led_strip_spi.h, led_strip/include/led_strip_types.h, led_strip/src/led_strip_rmt_dev_idf4.c
Added api.md according to approach described in 
https://github.com/espressif/idf-extra-components/issues/248
Fixed the wrong mem_block_num configuration in the *led_strip_rmt_dev_idf4.c*
=> docs(led_strip): add api reference

onewire_bus/README.md, onewire_bus/idf_component.yml, onewire_bus/src/onewire_bus_impl_rmt.c
the callback function is short, putting it in iram can reduce cache miss, and also allow the user to enable the `CONFIG_RMT_ISR_IRAM_SAFE`
Closes https://github.com/espressif/idf-extra-components/issues/266
=> change(onewire): put callback function in iram

esp_jpeg/examples/get_started/main/idf_component.yml, esp_jpeg/idf_component.yml
Fix for this error: https://github.com/espressif/idf-extra-components/actions/runs/7004078689/job/19060622718?pr=271
=> esp_jpeg: Fix BSP versions for using new version of button component (without warnings in new IDF).

catch2/cmd_catch2.cpp, catch2/idf_component.yml
This PR fixes a warning issued when catch2 component was used with IDF_TARGET=linux on a macOS host.
macOS version of ranlib issues a warning when it encounters a static library with no extern symbols.
When building catch2 component with IDF_TARGET=linux, the only object file in the library (cmd_catch2.cpp.obj) would indeed define no symbols, so libespressif__catch2.a would define no symbols as well, resulting in this warning.
Fix this by defining a dummy register_catch2 function even when building for IDF_TARGET=linux.
=> fix(catch2): work around ranlib warning when building on macOS

nghttp/CMakeLists.txt, nghttp/idf_component.yml, nghttp/port/include/nghttp2/nghttp2ver.h, nghttp/port/private_include/config.h, nghttp/sbom_nghttp2.yml
For detailed release notes please refer to:
https://github.com/nghttp2/nghttp2/releases/tag/v1.58.0
Security related:
- Release v1.57.0 fixes CVE-2023-44487
- Release v1.55.1 fixes CVE-2023-35945
=> nghttp2: update library to v1.58.0

json_generator/idf_component.yml, json_generator/include/json_generator.h, json_generator/src/json_generator.c
The latest commit from the source repository (https://github.com/espressif/json_generator/commit/17507cce331e8e2056593dc01f5adf0a8b6f63ef) was missing here
=> json_generator: Use consts wherever applicable (IEC-73)

usb/esp_tinyusb/CMakeLists.txt, usb/esp_tinyusb/idf_component.yml
Changes required for future extension of supported targets. 
- Removed `REQUIRED_IDF_TARGETS` from CMakeLists.txt to handle supported targets only with manifest file. 
- Removed targets from idf_component.yml. Now the target dependency will be handled only by the dependency components.
=> feat(usb/esp_tinyusb): Update manifest file

.github/workflows/vulnerability_scan.yml
This replaces the current approach to use the new esp-idf-sbom-action.
=> feat: use esp-idf-sbom-action for vulnerability scan

usb/esp_tinyusb/CHANGELOG.md, usb/esp_tinyusb/Kconfig, usb/esp_tinyusb/idf_component.yml, usb/esp_tinyusb/include/tusb_config.h
- Added USB OTG PHY HS configuration in KConfig for ESP32P4
Hint: For better experience and verification use TinyUSB v0.15.0~4
=> esp_tinyusb v1.4.3:  ESP32P4 HS only support

.github/workflows/build_and_run_examples.yml, .github/workflows/build_and_run_test_app.yml, .github/workflows/build_and_run_test_app_usb.yml
Add esp-idf release-v5.1 and release-v5.2 to CI build and test jobs.
Migrating to idf-build-apps will be done in a different PR
Related https://github.com/espressif/idf-extra-components/issues/16 and https://github.com/espressif/idf-extra-components/issues/149
=> feat(ci): Build with IDF 5.1 and 5.2

.github/workflows/build_and_run_examples.yml, esp_lcd_qemu_rgb/README.md, esp_lcd_qemu_rgb/examples/lcd_qemu_rgb_panel/main/lcd_qemu_rgb_panel_main.c, esp_lcd_qemu_rgb/idf_component.yml, esp_lcd_qemu_rgb/interface/esp_lcd_qemu_rgb.h, esp_lcd_qemu_rgb/src/esp_lcd_qemu_rgb.c, esp_lcd_qemu_rgb/src/esp_lcd_qemu_rgb_struct.h
=> feat(esp_qemu_rgb_panel): implement 16bpp QEMU RGB panel (IEC-77)

led_strip/idf_component.yml, led_strip/src/led_strip_rmt_encoder.c
WS2812B-V5 requires >280 microsecond reset time.
When led_strip with 50 microsecond reset time is used with WS2812B-V5 LEDs, most will handle reset correctly, but about 1/3 of certain transmission patterns would cause 1-2 LEDs in a long strip to fail to reset, leading to duplicated colors further down the led strip. Increase the reset time to 280 microseconds, which is compatible with led pixels requiring 50+ microsecond reset time as well.
=> led_strip: Add support for WS2812B-V5  (IEC-84)

expat/idf_component.yml, expat/port/include/expat_config.h, expat/sbom_libexpat.yml
Update expat to v2.6.0
This update includes some security fixes:
* CVE-2023-52425
* CVE-2023-52426
Release Notes: https://github.com/libexpat/libexpat/releases/tag/R_2_6_0
=> expat: Update version to v2.6.0

catch2/idf_component.yml, catch2/sbom_catch2.yml
This PR updates Catch2 from 3.4.0 to 3.5.2. I have tested that both examples still work.
=> feat(catch2): update to 3.5.2

expat/idf_component.yml, expat/port/include/expat_config.h, expat/sbom_libexpat.yml
Update expat to v2.6.2
It includes some security fixes:
* CVE-2024-28757
Changelog: https://github.com/libexpat/libexpat/releases/tag/R_2_6_2
=> feat: Update expat to v2.6.2

freetype/CMakeLists.txt, freetype/idf_component.yml
1. Remove system lib dependencies: If the package required by `find_package` (such as `BrotliDec`, `HarfBuzz`) exists locally on Linux, the local lib will be used, causing compilation failure.
`-- Found BrotliDec: /usr/include (found version "1.0.9")`
`-- HarfBuzz (required): /usr/lib/x86_64-linux-gnu/libharfbuzz.so`
`/usr/include/stdlib.h:258:25: error: '_Float64x' is not supported on this target`
=> fix(freetype): Remove system lib dependencies (IEC-103)

coap/Kconfig, coap/idf_component.yml
Add config option to enable/disable Q-Block option
Fixes: https://github.com/espressif/idf-extra-components/issues/324
=> fix(coap): Add config option to enable/disable Q-Block option

coap/CMakeLists.txt, coap/idf_component.yml, coap/port/coap_mbedtls.c
The fix has been merged in upstream repository: https://github.com/obgm/libcoap/pull/1381
Adding the fix in port directory. Will remove this when the fix is available in a libcoap release.
=> fix: Fix build failures in coap_client example with MbedTLS v3.6.0

ccomp_timer/CMakeLists.txt, ccomp_timer/idf_component.yml
The perfmon component is supported[1] only on xtensa arch, so it should not be in requires for other archs.
[1] https://github.com/espressif/esp-idf/blob/master/components/perfmon/CMakeLists.txt#L9-L11
Fixes: 5d61b5047f37 ("test_utils: implement performance timer")
=> fix(ccomp_timer): require perfmon only on xtensa

.github/workflows/upload_component.yml, .gitmodules, supertinycron/CMakeLists.txt, supertinycron/Kconfig, supertinycron/LICENSE.txt, supertinycron/README.md, supertinycron/examples/cron_example/CMakeLists.txt, supertinycron/examples/cron_example/README.md, supertinycron/examples/cron_example/main/CMakeLists.txt, supertinycron/examples/cron_example/main/cron_example_main.c, supertinycron/examples/cron_example/main/idf_component.yml, supertinycron/idf_component.yml, supertinycron/sbom_supertinycron.yml, test_app/CMakeLists.txt
=> Add ccronexpr components for parse CRON expression (IEC-88)

.github/workflows/clang-tidy.yml
- Fix failing clang-tidy job due to `libtinfo5` package not being found. This package is not needed anymore for recent IDF clang toolchain versions.
- ~~Upgrade clang-tidy-sarif. This includes a feature added in clang-tidy-sarif v0.3.6, now "note" messages from clang-tidy will be included into SARIF output.~~ — fails due to duplicate entries in generated SARIF. Will fix this in clang-tidy-sarif and upgrade it later.
=> ci: remove libtinfo5 installation

onewire_bus/src/onewire_bus_impl_rmt.c
Specifically this is the time that's necessary to be able to perform a device search on a bus consisting of >= 6 devices on >= 10m of wire at 5V with a 4.7 kΩ pull-up resistor.
=> fix(onewire): raise recovery time to support more sensor on longer wire (IEC-111)

onewire_bus/CHANGELOG.md, onewire_bus/idf_component.yml
Thanks to https://github.com/espressif/idf-extra-components/pull/329
let's bump up version to 1.0.2
=> change(1wire): bump up version to 1.0.2

network_provisioning/CHANGELOG.md, network_provisioning/examples/thread_prov/README.md, network_provisioning/examples/thread_prov/main/app_main.c, network_provisioning/examples/thread_prov/main/idf_component.yml, network_provisioning/examples/wifi_prov/README.md, network_provisioning/examples/wifi_prov/main/app_main.c, network_provisioning/examples/wifi_prov/main/idf_component.yml, network_provisioning/idf_component.yml, network_provisioning/proto/CMakeLists.txt, network_provisioning/src/manager.c, network_provisioning/tool/esp_prov/esp_prov.py
Add `wifi_prov` or `thread_prov` in provision capabilities for the provisioner to distinguish Thread or Wi-Fi devices.
=> feat(network_prov): Add wifi_prov or thread_prov in provision capabilities (IEC-105)

ccomp_timer/test/CMakeLists.txt
See https://github.com/espressif/esp-idf/commit/fbe8bf89ee4431c72631bc227bf7008cb3aa024e for more info
Fixes https://github.com/espressif/idf-extra-components/actions/runs/9350549394/job/25734263046?pr=332
=> fix(test): correctly declare ccomp_timer test_app dependencies

thorvg/CMakeLists.txt, thorvg/idf_component.yml, thorvg/sbom_thorvg.yml
ESP-IDF only use static library, and the thorvg library won't be linked into a dynamic library.
This PR also enables the multi-threading feature in thorvg.
```
Summary:
ThorVG version:             0.13.6
Build Type:                 debugoptimized
Prefix:                     /usr/local
Multi-Tasking:              true                        <------------- Enabled in this PR
SIMD Instruction:           none
Raster Engine (SW):         true
Raster Engine (GL_BETA):    false
Raster Engine (WG_BETA):    false
Loader (TVG):               true
Loader (SVG):               true
Loader (TTF):               false
Loader (LOTTIE):            true
Loader (PNG):               false
Loader (JPG):               false
Loader (WEBP):              false
Saver (TVG):                false
Saver (GIF): …
```
=> fix(thorvg): build static library without -fPIC

led_strip/idf_component.yml, led_strip/src/led_strip_spi_dev.c
This commit add a delay to ensure that the reset time is enough during the initialization. And remove the rigorous judgment of the real spi clk resolution to support different XTAL freq.
https://github.com/espressif/idf-extra-components/issues/340
=> fix(led_strip): fix the reset time and resolution bugs (IEC-124)

.github/workflows/build_and_run_examples.yml, .github/workflows/build_and_run_test_app.yml
Temporary fix for the following error on the self hosted runners:
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
We can revert this change once we fix the runners. 
More on the issue:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> fix(ci): allow unsecure node version for self hosted runner

nghttp/CMakeLists.txt, nghttp/idf_component.yml, nghttp/port/include/nghttp2/nghttp2ver.h, nghttp/sbom_nghttp2.yml
Updated the nghttp2 submodule from v1.58.0 or v1.62.1. 
Testing -
Tested this component using the example which is in sh2lib component. Checked whether this example runs before and           after upgrading the nghttp2
Binary size (http2_request.bin) -
Before - 1015120 Bytes
After - 1015536 Bytes
Library Size (libnghttp.a) -
Before - 82712 Bytes
After - 83087 Bytes
Link to changelog -
https://github.com/nghttp2/nghttp2/releases/tag/v1.62.1
=> updated nghttp2 component (IEC-132)

network_provisioning/CHANGELOG.md, network_provisioning/examples/thread_prov/main/idf_component.yml, network_provisioning/examples/wifi_prov/main/idf_component.yml, network_provisioning/idf_component.yml, network_provisioning/proto-c/network_config.pb-c.c, network_provisioning/proto-c/network_config.pb-c.h, network_provisioning/proto-c/network_constants.pb-c.c, network_provisioning/proto-c/network_constants.pb-c.h, network_provisioning/proto-c/network_ctrl.pb-c.c, network_provisioning/proto-c/network_ctrl.pb-c.h, network_provisioning/proto-c/network_scan.pb-c.c, network_provisioning/proto-c/network_scan.pb-c.h, network_provisioning/proto/network_config.proto, network_provisioning/proto/network_constants.proto, network_provisioning/proto/network_ctrl.proto, network_provisioning/proto/network_scan.proto, network_provisioning/python/network_config_pb2.py, network_provisioning/python/network_constants_pb2.py, network_provisioning/python/network_ctrl_pb2.py, network_provisioning/python/network_scan_pb2.py, network_provisioning/src/network_config.c, network_provisioning/src/network_ctrl.c, network_provisioning/src/network_scan.c, network_provisioning/tool/esp_prov/README.md, network_provisioning/tool/esp_prov/esp_prov.py, network_provisioning/tool/esp_prov/prov/network_ctrl.py, network_provisioning/tool/esp_prov/prov/network_prov.py, network_provisioning/tool/esp_prov/prov/network_scan.py
Change the protobuf files so that the network_provisioning component will stay backward compatible with wifi_provisioning
- Provision `thread_prov`&`wifi_prov` examples in this component and `wifi_prov_mgr` example in ESP-IDF using `esp_prov.py` script in this component. (So phone Apps using the proto files in this component can provision previous firmware using `wifi_provisioning`)
- Provision `wifi_prov` example in this component and `wifi_prov_mgr` example in ESP-IDF using `esp_prov.py` script in ESP-IDF (So phone Apps using proto files in `wifi_provisioning` component can provision wifi firmware using `network_provisioning`)
=> feat(network_prov): Change the proto file to make the network_provisioning stay backward compatible with wifi_provisioning (IEC-125)

fmt/LICENSE, fmt/LICENSE.rst, fmt/examples/hello_fmt/CMakeLists.txt, fmt/examples/hello_fmt/README.md, fmt/examples/hello_fmt/main/CMakeLists.txt, fmt/examples/hello_fmt/main/hello_fmt.cpp, fmt/examples/hello_fmt/main/idf_component.yml, fmt/examples/hello_fmt/pytest_fmt.py, fmt/idf_component.yml, fmt/sbom_fmt.yml
- Added a simple example to `fmt` component and a test to check that the example works
- Updated `fmt` to 11.0.1
=> Update fmt to 11.0.1, add example

spi_nand_flash/examples/nand_flash/main/spi_nand_flash_example_main.c, spi_nand_flash/idf_component.yml, spi_nand_flash/src/nand.c, spi_nand_flash/src/nand_flash_devices.h, spi_nand_flash/test_app/main/idf_component.yml
Add support for the Micron MT29F nand chip, tested specifically on `MT29F4G01ABAFDWB`
=> added support for Micron MT29F nand flash (IEC-110)

.github/workflows/build_and_run_examples.yml, .github/workflows/build_and_run_test_app.yml
- Removed IDF release-v4.4 build and tests as the branch is now EOL
=> fix: add support for release-v5.3 branch build and tests

fmt/README.md
An embarrassingly simple "fix". The correct link is
https://github.com/fmtlib/fmt/blob/master/README.md not
https://github.com/fmtlib/fmt/blob/master/README.rst
...and apparently has been since fmt was uploaded to Github in 2012.
=> fmt: fix link to parent project in README.md (IEC-145)

coap/sbom_libcoap.yml, expat/sbom_libexpat.yml, nghttp/sbom_nghttp2.yml
These CVEs have not yet been analyzed in the NVD and were identified by the esp-idf-sbom checker during a keyword search in the CVE descriptions. Since the affected components have already been updated to newer versions, these CVEs are no longer relevant to the current version. Therefore, they should be added to the exclude list.
=> change: exclude CVEs that have already been resolved

network_provisioning/idf_component.yml, network_provisioning/src/scheme_softap.c
There is an issue for network_prov_scheme_softap. Fix it in this PR.
=> fix(network_prov): fix provisioning over softap (IEC-161)

expat/idf_component.yml, expat/port/include/expat_config.h, expat/sbom_libexpat.yml
Update the libexpat to version 2.6.3
Updated libexpat to version 2.6.3
https://github.com/libexpat/libexpat/blob/R_2_6_3/expat/Changes
| Before  | After   |
|---------|---------|
| 1361632 | 1361664 |
=> feat(libexpat): Updated libexpat to version 2.6.3

expat/idf_component.yml, expat/sbom_libexpat.yml
This CVE has not yet been processed in the NVD and was previously excluded in https://github.com/espressif/idf-extra-components/pull/359. Unfortunately, the update to libexpat version 2.6.3 removed it in https://github.com/espressif/idf-extra-components/pull/372. This change re-adds CVE-2024-28757 to the exclude list.
=> change: exclude CVE-2024-28757 for libexpat

thorvg/idf_component.yml
https://github.com/espressif/idf-extra-components/actions/runs/10919154946/job/30306218942?pr=377 — thorvg component archive size is 80 MB, and the upload process times out.
This PR excludes some of the component directories, reducing the archive size to 1.4 MB.
Testing:
- ran `compote component upload --name thorvg --namespace espressif --dry-run`
- unpacked the component archive in `dist` directory and built the example from it
Component version not bumped because the upload after the previous bump wasn't successful.
=> fix(thorvg): exclude some folders to reduce component size

.build-test-rules.yml, catch2/examples/catch2-console/pytest_catch2_console.py, catch2/examples/catch2-test/pytest_catch2.py, catch2/idf_component.yml, catch2/sbom_catch2.yml
Upstream changes: https://github.com/catchorg/Catch2/compare/v3.5.2...v3.7.0
Have also added pytest cases to check catch2 examples in CI.
=> feat(catch2): update to 3.7.0

coremark/CMakeLists.txt, coremark/idf_component.yml, coremark/linker.lf.in
Closes https://github.com/espressif/idf-extra-components/issues/368
=> fix(coremark): archive in linker.lf should depend on component name

.github/README.md, .github/get_idf_build_apps_args.py, .github/workflows/build_and_run_apps.yml
1. Fix the pipeline failure when there were no builds — if no components were changed in a PR, `get_idf_build_apps_args.py` produced `--modified-components` flag without an argument, leading to idf-build-apps failing: https://github.com/espressif/idf-extra-components/actions/runs/11072864141/job/30768082599?pr=390.
Fixed by adding a check for modified_files and modified_components to the script.
2. Fix the pipeline failure when there were no tests to run — if the components changed in the PR didn't have pytest cases, all tests were ignored and pytest would exit with code 5: https://github.com/espressif/idf-extra-components/actions/runs/11111027174/job/30870632120.
Fixed using [pytest-custom-exit-code](https://pypi.org/project/pytest-custom-exit-code/) plugin and …
=> ci: fix workflow when there are no builds or no tests

spi_nand_flash/CMakeLists.txt, spi_nand_flash/examples/nand_flash/main/spi_nand_flash_example_main.c, spi_nand_flash/idf_component.yml, spi_nand_flash/sbom_dhara.yml, spi_nand_flash/test_app/CMakeLists.txt, spi_nand_flash/test_app/main/CMakeLists.txt, spi_nand_flash/test_app/main/test_app_main.c, spi_nand_flash/test_app/main/test_spi_nand_flash.c
* add dhara to public requirements
Since 892d994e8b3ee1bdf32ca49513a709c44ee9c12f, spi_nand_flash.h includes dhara/map.h, so dhara should be a public dependency of spi_nand_flash.
Other changes:
- move vfs to private requirements (it didn't have to be public)
- depend specifically on `esp_driver_spi` instead of `driver` when building for IDF >=5.3
* fix memory leaks in test (free temporary buffers) and raise leak threshold to not detect esp_intr_alloc lazy allocation as a leak
* add read/write performance output to the test case
* remove unused sbom_dhara.yml file from spi_nand_flash component
* version changed from 0.3.1 to 0.4.0 since removing `vfs` from the public requirements is technically a breaking change
=> fix(spi_nand_flash): add dhara to public dependencies (+minor changes)

esp_jpeg/idf_component.yml, esp_jpeg/jpeg_decoder.c
add swap_color_bytes for rgb888 to get pixels in rgb/bgr order.
=> [fix] add swap_color_bytes for rgb888. (IEC-160)

coap/idf_component.yml, coap/sbom_libcoap.yml
This was fixed by 4851806c09a9 ("scan-build: CI Fail if scan-build warnings") in v4.3.5-rc3.
=> change(coap): exclude CVE-2024-46304

freetype/CMakeLists.txt, freetype/idf_component.yml, freetype/sbom_freetype.yml
This PR updates freetype from 2.13.0 to 2.13.3.
Among other changes, this fixes CMake warning:
```
CMake Deprecation Warning at idf-extra-components/freetype/freetype/CMakeLists.txt:113 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
=> feat(freetype): update to 2.13.3

spi_nand_flash/src/nand.c, spi_nand_flash/src/nand_flash_devices.h
Added support for MT29F1G01ABAFDSF-AAT:F chip
=> Feat/spi nand flash mt29f1 (IEC-225)

expat/idf_component.yml, expat/port/include/expat_config.h, expat/sbom_libexpat.yml
Release notes:
https://github.com/libexpat/libexpat/releases/tag/R_2_6_4
Fixes CVE-2024-50602
=> feat: upgrade the expat component to latest 2.6.4 release

network_provisioning/idf_component.yml, network_provisioning/src/handlers.c, network_provisioning/src/network_scan.c
For some examples which download this managed component of network_provisioning it could never use this component (neither `CONFIG_NETWORK_PROV_NETWORK_TYPE_WIFI` nor `CONFIG_NETWORK_PROV_NETWORK_TYPE_THREAD` not selected ) but the examples would compile the sources in the component. which would result in the warnings of `unused_function` or `unused_variable`.
=> fix(network_prov): Fix warning of unused_function or unused_variable (IEC-227)

esp_jpeg/CHANGELOG.md, esp_jpeg/README.md, esp_jpeg/examples/get_started/sdkconfig.defaults, esp_jpeg/idf_component.yml, esp_jpeg/include/jpeg_decoder.h, esp_jpeg/jpeg_decoder.c, esp_jpeg/test_apps/main/tjpgd_test.c
Add configuration option for working buffer size
=> feat(esp_jpeg): Add configuration option for working buffer size

.github/workflows/vulnerability_scan.yml
esp-idf-sbom offers two ways to perform vulnerability scanning. The primary method, which is the default, uses the NVD REST API. The alternative method uses the esp-nvd-mirror repository. If there are issues with accessing the NVD REST API, it can be useful to switch to the esp-nvd-mirror easily. Allow to set the SBOM_CHECK_LOCAL_DB github repository variable to switch to esp-nvd-mirror.
=> feat(ci): pass SBOM_CHECK_LOCAL_DB to esp-idf-sbom-action

.github/workflows/clang-tidy.yml
The issue is that recent modifications[1] to the ESP-IDF export scripts allow them to identify the export script path only for bash and zsh. For other shells, the export must be executed from within the ESP-IDF directory.
The problem is because the default shell in a GitHub step inside a container is sh instead of bash[2].
> The default shell for run steps inside a container is sh instead of
bash. This can be overridden with jobs.<job_id>.defaults.run or jobs.<job_id>.steps[*].shell.
[1] https://github.com/espressif/esp-idf/commit/cad15b50c40ba1fcb1f63c106805f498c3fc971c
[2] https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
=> ci: fix pyclang install

esp_encrypted_img/CHANGELOG.md, esp_encrypted_img/idf_component.yml, esp_encrypted_img/src/esp_encrypted_img.c
version from 2.2.1 to 2.2.2
Upgraded the esp_encrypted_ota component version from 2.2.1 to 2.2.2.
=> feat(esp_encrypted_ota): Upgraded the esp_encrypted_img component

led_strip/examples/led_strip_rmt_ws2812/main/led_strip_rmt_ws2812_main.c
ESP32S3 mem_block_symbols must be a multiple of 48 on the ESP32S3. Setting this to 0 in the example allows the driver to use this automatically. Right now the example is broken in ESP32-S3.
=> Fixes bug in led_strip_rmt_ws2812 example (IEC-250)

coap/examples/coap_server/main/coap_server_example_main.c, coap/idf_component.yml, coap/sbom_libcoap.yml
Addition of support for server initiated CoAP keepalive packets to garbage collect stale observation requests when the client goes away.
=> feat(coap); Support for server keepalives (IEC-254)

esp_delta_ota/CHANGELOG.md, esp_delta_ota/examples/https_delta_ota/tools/esp_delta_ota_patch_gen.py, esp_delta_ota/idf_component.yml
- esp_delta_ota_patch_gen.py script not working on windows, as esptool.py and mv command were executed through python and not recognised by windows command shell.
- Refactored the esp_delta_ota_patch_gen script
- Integrated the esptool module
- Utilized the detools module apis
1. These changes are tested on Windows, Mac and Linux.
2. Calculated the md5 hash for the patch generated by the script before changes and after changes, both output the same hash.
=> fix(esp_delta_ota): Fix esp_delta_ota_patch_gen script

freetype/sbom_freetype.yml
Adds CVE-2025-27363 to CVE exclude list. This CVE only affects version 2.13.0 and below as per [NIST](https://nvd.nist.gov/vuln/detail/CVE-2025-27363) database.
The freetype version in use is 2.13.3 which isn't affected by this CVE.
=> change(freetype): add CVE-2025-27363 to cve exclude list (IEC-283)

led_strip/CHANGELOG.md, led_strip/examples/led_strip_rmt_ws2812/main/led_strip_rmt_ws2812_main.c, led_strip/idf_component.yml
Adds a DMA example for the RMT led_strip. Created by [suda-morris](https://github.com/suda-morris)
- [x ] Component contains License
- [ x] Component contains README.md
- [ x] Component contains idf_component.yml file with `url` field defined
- [ x] Component was added to [upload job](https://github.com/espressif/idf-extra-components/blob/master/.github/workflows/upload_component.yml#L18)
- [x ] Component was added to [build job](https://github.com/espressif/idf-extra-components/blob/master/test_app/CMakeLists.txt#L8)
- [- ] _Optional:_ Component contains unit tests - Manually tested espressif solution set for rmt dma mode, then uploaded.
=> Create led_strip_rmt_ws2812.c (IEC-253)

spi_nand_flash/src/nand_impl.c
ESP32-C3 is based on the RISC-V architecture and does not allow uint16_t to be memory-aligned like ESP32. As a result, reading bad blocks caused a memory alignment error. This PR fixes the issue.
=> fix(spi_nand_flash): fix memory alignment issue occurring on esp32c3

spi_nand_flash/examples/nand_flash/README.md, spi_nand_flash/examples/nand_flash/main/spi_nand_flash_example_main.c, spi_nand_flash/idf_component.yml, spi_nand_flash/include/spi_nand_flash.h, spi_nand_flash/priv_include/nand.h, spi_nand_flash/priv_include/spi_nand_oper.h, spi_nand_flash/src/nand.c, spi_nand_flash/src/nand_alliance.c, spi_nand_flash/src/nand_gigadevice.c, spi_nand_flash/src/nand_impl.c, spi_nand_flash/src/nand_micron.c, spi_nand_flash/src/nand_winbond.c, spi_nand_flash/src/spi_nand_oper.c, spi_nand_flash/test_app/main/test_spi_nand_flash.c
spi_nand_flash: Added standard (full-duplex), DIO, DOUT spi mode support.
QIO mode support will be added in another PR
=> feat(spi_nand_flash): Add SIO (full-duplex) and DIO mode support

network_provisioning/CHANGELOG.md, network_provisioning/idf_component.yml, network_provisioning/src/manager.c, network_provisioning/tool/esp_prov/esp_prov.py, network_provisioning/tool/esp_prov/security/security2.py
The security2 scheme in protocomm component has been update to fix incorrect AES-GCM IV usage, so we need to update network_provisioning to make it work with the new security2 scheme.
=> fix(network_prov): fix incorrect AES-GCM IV usage in security2 scheme (IEC-279)

spi_nand_flash/examples/nand_flash_debug_app/main/spi_nand_flash_debug_app_main.c, spi_nand_flash/idf_component.yml, spi_nand_flash/include/spi_nand_flash.h, spi_nand_flash/priv_include/nand.h, spi_nand_flash/priv_include/spi_nand_oper.h, spi_nand_flash/src/nand.c, spi_nand_flash/src/nand_alliance.c, spi_nand_flash/src/nand_gigadevice.c, spi_nand_flash/src/nand_micron.c, spi_nand_flash/src/nand_winbond.c, spi_nand_flash/src/spi_nand_oper.c, spi_nand_flash/test_app/main/test_spi_nand_flash.c
spi_nand_flash: Added QIO and QOUT spi mode support
Performance Comparison across all SPI modes on 40M SPI bus frequency:
```
SIO:
Wrote 131072 bytes in 111909 us, avg 1171.24 kB/s
Read 131072 bytes in 41334 us, avg 3171.05 kB/s
DIO:
Wrote 131072 bytes in 115245 us, avg 1137.33 kB/s
Read 131072 bytes in 27383 us, avg 4786.62 kB/s
DOUT:
Wrote 131072 bytes in 115222 us, avg 1137.56 kB/s
Read 131072 bytes in 27414 us, avg 4781.21 kB/s
QIO:
Wrote 131072 bytes in 90107 us, avg 1454.63 kB/s
Read 131072 bytes in 20829 us, avg 6292.76 kB/s
QOUT:
Wrote 131072 bytes in 90098 us, avg 1454.77 kB/s
Read 131072 bytes in 20848 us, avg 6287.03 kB/s
```
=> feat(spi_nand_flash): Add QIO mode support

network_provisioning/CHANGELOG.md, network_provisioning/CMakeLists.txt, network_provisioning/Kconfig, network_provisioning/idf_component.yml
- In cases, such as ESP32-P4, we do not have native Wi-Fi and it uses other
mechanisms., such as esp-hosted.[ esp-wifi-remote ](https://github.com/espressif/esp-wifi-remote)is used in this case.
- Provisioning component currently check if Wi-Fi is natively
enabled for it to compile wifi_provisioning sources.
This causes link errors when enabling the provisiong for ESP32-P4
- Extend the check for Wi-Fi remote as well, so the sources are compiled. (The config option itself comes from esp-wifi-remote)
This change extends the provisioning support for the devices(such as P4+C6 setup using esp_hosted for connectivity) using Wi-Fi remotes.
- Also bumped up the patch version for network_provisioning component
=> fix(network_provisioning): Consider WIFI_REMOTE for provisioning (IEC-260)

nghttp/idf_component.yml, nghttp/port/include/nghttp2/nghttp2ver.h, nghttp/sbom_nghttp2.yml
- Upgraded the nghttp2 to 1.65.0
- Checked the CVE using esp-idf-sbom tool
Closes https://github.com/espressif/idf-extra-components/issues/490
=> feat(nghttp): Upgrade the nghttp2 to 1.65.0

onewire_bus/CHANGELOG.md, onewire_bus/CMakeLists.txt, onewire_bus/README.md, onewire_bus/idf_component.yml, onewire_bus/src/onewire_bus_impl_rmt.c
The rmt driver in esp-idf v6.0 removes some deprecated config options like io_loop_back and io_od_mode. This PR is to adapt that change.
Tested passed locally with the following packages:
```
NOTICE: [1/3] ds18b20 (0.1.2) (/home/morris/esp/esp-bsp/components/ds18b20)
NOTICE: [2/3] onewire_bus (1.0.3) (/home/morris/esp/idf-extra-components/onewire_bus)
NOTICE: [3/3] idf (6.0.0)
```
=> refactor(1wire): improve the driver to support esp-idf v6

.github/workflows/build_and_run_apps.yml
- Added release/v5.4 (which was created a while ago but I missed to add it here)
- Added release/v5.5, pushed to Github recently
release/v5.0 will be EoL at the end of the month and will be removed then.
=> change(ci): add release/v5.4 and release/v5.5 branches to test matrix

cbor/CMakeLists.txt, cbor/idf_component.yml
1. Updated the CMakelists.txt of cobra component. Removed the check which undefines __STDC_HOSTED__ if clang toolchain is used.
2. Tested with idf releases v5.1, v5.2, v5.3, v5.4 and master.
=> Clang support for cbor component fix

esp_delta_ota/CHANGELOG.md, esp_delta_ota/examples/https_delta_ota/README.md, esp_delta_ota/idf_component.yml
1. In README.md python command for creating patch was incorrect
2. Mentioned python command to verify the patch
3. This is due to we recently modified the python tool for creating patch. [!MR](https://github.com/espressif/idf-extra-components/pull/396/files)
=> Updated the README.md of esp_delta_ota to fix command issue

.github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/upload_component.yml, .idf_build_apps.toml, esp_gcov/CMakeLists.txt, esp_gcov/Kconfig, esp_gcov/LICENSE, esp_gcov/README.md, esp_gcov/esp_gcov.h, esp_gcov/gcov_rtio.c, esp_gcov/idf_component.yml, esp_gcov/io_sym.map, esp_gcov/project_include.cmake
Add esp-gcov component for ESP-IDF code coverage support
=> Add esp-gcov for code coverage support (IEC-342)

esp_gcov/Kconfig.gcov, esp_gcov/idf_component.yml
Enable IPC by default from the esp_gcov component to avoid external config dependency in the IDF.
Kconfig file renamed as Kconfig.gcov to allow importing from app_trace/Kconfig file
=> fix(esp_gcov): ipc enabled by default (IEC-345)

sh2lib/sh2lib.c, sh2lib/sh2lib.h
Enable configuring ESP-TLS TCP KeepAlive config pointer
=> feat(sh2lib): TCP keepalive configuration (IEC-367)

esp_isotp/Kconfig, esp_isotp/README.md, esp_isotp/inc/esp_isotp.h, esp_isotp/src/esp_isotp.c
This PR enhances the `esp_isotp` component with thread safety, event-driven callbacks, and extended feature support, transforming it from a basic polling implementation to a production-ready ISO-TP communication library.
- **ISR-safe send functions**: `esp_isotp_send()` and `esp_isotp_send_with_id()` can be called from interrupt context
- **Spinlock protection**: Core state protected with `portMUX` locks to prevent race conditions
- **TX frame buffer pool**: Pre-allocated memory pool eliminates stack corruption in async TWAI operations
- **Asynchronous notifications**: Optional `rx_callback` and `tx_callback` in configuration
- **Non-blocking operation**: Eliminates need for continuous polling in callback mode
- **29-bit ID support**: Added `use_extended_id` configuration option
- …
=> feat(isotp): Add thread safety, callbacks, and extended ID support (IEC-370)

.codespellrc, .github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/upload_component.yml, .idf_build_apps.toml, esp_daylight/.build-test-rules.yml, esp_daylight/CHANGELOG.md, esp_daylight/CMakeLists.txt, esp_daylight/LICENSE, esp_daylight/README.md, esp_daylight/examples/get_started/CMakeLists.txt, esp_daylight/examples/get_started/README.md, esp_daylight/examples/get_started/main/CMakeLists.txt, esp_daylight/examples/get_started/main/esp_daylight_example_main.c, esp_daylight/examples/get_started/main/idf_component.yml, esp_daylight/examples/get_started/pytest_esp_daylight_example.py, esp_daylight/idf_component.yml, esp_daylight/include/esp_daylight.h, esp_daylight/src/esp_daylight.c, esp_daylight/test_apps/CMakeLists.txt, esp_daylight/test_apps/main/CMakeLists.txt, esp_daylight/test_apps/main/idf_component.yml, esp_daylight/test_apps/main/test_app_main.c, esp_daylight/test_apps/main/test_esp_daylight.c, esp_daylight/test_apps/pytest_esp_daylight.py, esp_daylight/test_apps/sdkconfig.defaults
This adds a component esp_daylight which can be used to find sunrise/sunset timings at given locations (based on latitude and longitude) using NOAA Solar Calculator. Reference: https://gml.noaa.gov/grad/solcalc/
=> Task/esp_daylight (IEC-374)

expat/sbom_libexpat.yml
The expat was updated to version 2.7.2 to fix [CVE-2025-59375](https://nvd.nist.gov/vuln/detail/CVE-2025-59375) with this [PR](https://github.com/espressif/idf-extra-components/pull/573)
However the Github vulnerability scan still reports this vulnerability: https://github.com/espressif/idf-extra-components/actions/runs/17814199758
This PR adds the CVE to the exclude list.
=> change(expat): exclude CVE-2025-59375

esp_jpeg/Kconfig
=> fix(jpeg): Fix a typo in kconfig

network_provisioning/CHANGELOG.md, network_provisioning/CMakeLists.txt, network_provisioning/idf_component.yml
If a project is already using the JSON component from IDF 5.x, it’s better to use the same component in network_provisioning as well.
For IDF 6.0 and later, we must use the cJSON component from the registry since it has been removed from the IDF.
=> feat(network_provisioning): use managed cJSON for IDF 6.0 and above
